"""adiciona data de encerramento na ordem de servico.

Revision ID: ab82da389fac
Revises: 6531db7ca46c
Create Date: 2026-06-16 19:04:54.555596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab82da389fac'
down_revision = '6531db7ca46c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_services', schema=None) as batch_op:
        batch_op.drop_column('closed_at')

    # ### end Alembic commands ###
